#!/usr/bin/env python3
"""Write data/projects.json from hunt briefs + original honest seed. No invented campuses."""
from __future__ import annotations

import json
from pathlib import Path

EMPTY_DATES = {
    "announcement": None,
    "sitework": None,
    "shell": None,
    "permanent_power": None,
    "L0": None,
    "L1": None,
    "L2": None,
    "L3": None,
    "L4": None,
    "L5": None,
    "L6": None,
    "IST": None,
    "RFS": None,
    "dqcx_pursuit_window_start": None,
    "dqcx_pursuit_window_end": None,
    "cx_award_target": None,
}

EMPTY_SCOPE = {
    "L0": "unknown",
    "L1": "unknown",
    "L2": "unknown",
    "L3": "unknown",
    "L4": "unknown",
    "L5": "unknown",
    "L6": "unknown",
    "IST": "unknown",
    "scripts": "unknown",
    "FAT": "unknown",
    "TAB": "unknown",
    "QAQC": "unknown",
}


def src(typ: str, quote: str, date: str, url: str = "") -> dict:
    return {"type": typ, "quote": quote, "date": date, "url": url}


def hunt_campus(**partial: object) -> dict:
    field_confidence = {"region": "inferred"}
    extra = partial.pop("field_confidence", None)
    if isinstance(extra, dict):
        field_confidence.update(extra)
    return {
        "project_id": partial["project_id"],
        "name": partial["name"],
        "aliases": partial.get("aliases") or [],
        "campus": partial.get("campus") or partial["name"],
        "building": None,
        "city": partial.get("city"),
        "state": partial.get("state"),
        "country": partial.get("country"),
        "region": partial["region"],
        "dq_number": None,
        "record_kind": "live",
        "project_type": "unknown",
        "it_mw": None,
        "critical_mw": None,
        "buildings": None,
        "high_density": None,
        "liquid_cool": None,
        "value_usd": None,
        "status": "watching",
        "owner": None,
        "developer": None,
        "tenant": None,
        "gc": None,
        "mep": None,
        "utility": None,
        "cxa_incumbent": None,
        "tab": None,
        "electrical_contractor": None,
        "mechanical_contractor": None,
        "oem_vendors": [],
        "bd_owner_internal": None,
        "cx_award_status": "unknown",
        "relationship": "unknown",
        "dates": dict(EMPTY_DATES),
        "scope_fit": dict(EMPTY_SCOPE),
        "next_action": "Enrich from primary source",
        "next_action_due": "2026-10-02",
        "sources": [],
        "field_confidence": field_confidence,
        "notes": partial["notes"],
    }


def dates(**overrides: object) -> dict:
    d = dict(EMPTY_DATES)
    d.update(overrides)
    return d


projects: list[dict] = []

projects.append(
    {
        "project_id": "dq-260022",
        "name": "Summit Project Horizon",
        "aliases": ["Project Horizon", "DQ 260022"],
        "campus": "Project Horizon",
        "building": None,
        "city": "Fort Stockton",
        "state": "TX",
        "country": "US",
        "region": "TX",
        "dq_number": "260022",
        "record_kind": "live",
        "project_type": "unknown",
        "it_mw": None,
        "critical_mw": None,
        "buildings": None,
        "high_density": None,
        "liquid_cool": None,
        "value_usd": 645435,
        "status": "keep_warm",
        "owner": None,
        "developer": None,
        "tenant": None,
        "gc": None,
        "mep": None,
        "utility": None,
        "cxa_incumbent": None,
        "tab": None,
        "electrical_contractor": None,
        "mechanical_contractor": None,
        "oem_vendors": [],
        "bd_owner_internal": "David Dinh",
        "cx_award_status": "pending",
        "relationship": "existing",
        "dates": dates(
            cx_award_target="2026-09-30",
            dqcx_pursuit_window_start="2026-09-01",
            dqcx_pursuit_window_end="2026-10-31",
        ),
        "scope_fit": dict(EMPTY_SCOPE),
        "next_action": "Keep warm with David Dinh — award pending September. Do not staff until owner/GC/L3 are sourced.",
        "next_action_due": "2026-09-22",
        "sources": [
            src(
                "internal",
                "DQ# 260022 — Summit Project Horizon, Fort Stockton TX. Award pending September. value_usd 645435. BD David Dinh. Status keep warm.",
                "2026-09-01",
            )
        ],
        "field_confidence": {
            "name": "confirmed",
            "city": "confirmed",
            "state": "confirmed",
            "region": "confirmed",
            "dq_number": "confirmed",
            "value_usd": "confirmed",
            "bd_owner_internal": "confirmed",
            "status": "confirmed",
            "cx_award_status": "confirmed",
            "relationship": "inferred",
            "dates.cx_award_target": "inferred",
            "it_mw": "unknown",
            "owner": "unknown",
            "gc": "unknown",
            "dates.L3": "unknown",
        },
        "notes": "Internal BD record only. MW, COD/L3, owner, GC, EPC, and Cx incumbent are unknown. Do not invent them.",
    }
)

projects.append(
    {
        "project_id": "dq-260013",
        "name": "ColoShield - NSCALE Cx",
        "aliases": ["ColoShield", "NSCALE Cx", "DQ 260013"],
        "campus": "ColoShield",
        "building": None,
        "city": None,
        "state": None,
        "country": None,
        "region": "Other",
        "dq_number": "260013",
        "record_kind": "live",
        "project_type": "unknown",
        "it_mw": None,
        "critical_mw": None,
        "buildings": None,
        "high_density": None,
        "liquid_cool": None,
        "value_usd": None,
        "status": "watching",
        "owner": None,
        "developer": None,
        "tenant": None,
        "gc": None,
        "mep": None,
        "utility": None,
        "cxa_incumbent": None,
        "tab": None,
        "electrical_contractor": None,
        "mechanical_contractor": None,
        "oem_vendors": [],
        "bd_owner_internal": None,
        "cx_award_status": "unknown",
        "relationship": "unknown",
        "dates": dates(),
        "scope_fit": dict(EMPTY_SCOPE),
        "next_action": "Confirm NSCALE Cx scope from a primary source. Do not book September revenue that is not sourced.",
        "next_action_due": "2026-09-28",
        "sources": [
            src(
                "internal",
                "DQ# 260013 — ColoShield - NSCALE Cx. Internal identifier only; no sourced MW, COD, EPC, or dollars.",
                "2026-09-01",
            )
        ],
        "field_confidence": {
            "name": "confirmed",
            "dq_number": "confirmed",
            "region": "unknown",
            "project_type": "unknown",
            "value_usd": "unknown",
            "it_mw": "unknown",
        },
        "notes": "Sparse CRM stub. Title includes NSCALE — that is not a sourced tenant or award. No invented September revenue.",
    }
)

projects.extend(
    [
        hunt_campus(
            project_id="hunt-oulu",
            name="Oulu",
            campus="Oulu",
            city="Oulu",
            country="Finland",
            region="Other",
            field_confidence={"city": "inferred", "country": "inferred", "region": "inferred"},
            notes="Hunt campus — name/location tokens only. Enrich from a primary source before any score move.",
        ),
        hunt_campus(
            project_id="hunt-goodnight",
            name="Goodnight",
            campus="Goodnight",
            region="Other",
            notes="Hunt campus — name only. No city, MW, COD, or parties on file.",
        ),
        hunt_campus(
            project_id="hunt-columbiana",
            name="Columbiana",
            campus="Columbiana",
            city="Columbiana",
            region="Other",
            field_confidence={"city": "inferred", "region": "unknown"},
            notes="Hunt campus — city token from the name. State, owner, MW unknown.",
        ),
        hunt_campus(
            project_id="hunt-smx01",
            name="SMX01",
            campus="SMX01",
            region="Other",
            notes="Hunt campus — site code only. Do not expand the acronym without a source.",
        ),
        hunt_campus(
            project_id="hunt-cloudburst-tx",
            name="CloudBurst TX",
            campus="CloudBurst",
            state="TX",
            country="US",
            region="TX",
            field_confidence={"state": "inferred", "region": "inferred", "country": "inferred"},
            notes="Hunt campus — Texas token from the name. No MW, COD, or counterparties.",
        ),
        hunt_campus(
            project_id="hunt-hyperion-richland",
            name="Hyperion Richland Parish",
            campus="Hyperion",
            city="Richland Parish",
            region="Other",
            field_confidence={"city": "inferred", "campus": "inferred", "region": "unknown"},
            notes="Hunt campus — locality token from the name. State/owner/MW unknown.",
        ),
        hunt_campus(
            project_id="hunt-tembo-cheyenne",
            name="Tembo Cheyenne",
            campus="Tembo",
            city="Cheyenne",
            region="Other",
            field_confidence={"city": "inferred", "campus": "inferred", "region": "unknown"},
            notes="Hunt campus — city token from the name. State/owner/MW unknown.",
        ),
        hunt_campus(
            project_id="hunt-clydesdale-owasso",
            name="Clydesdale Owasso",
            campus="Clydesdale",
            city="Owasso",
            region="Other",
            field_confidence={"city": "inferred", "campus": "inferred", "region": "unknown"},
            notes="Hunt campus — city token from the name. State/owner/MW unknown.",
        ),
    ]
)

# Post-race hunt briefs (Drive 2026-09-18 / 2026-09-17). Facts only from those files.
projects.append(
    {
        "project_id": "dq-hunt-cleanspark-sandersville",
        "name": "CleanSpark Sandersville",
        "aliases": ["Sandersville GA", "DQ-HUNT-CLEANSPARK-SANDERSVILLE"],
        "campus": "Sandersville",
        "building": None,
        "city": "Sandersville",
        "state": "GA",
        "country": "US",
        "region": "GA",
        "dq_number": None,
        "record_kind": "live",
        "project_type": "colo",
        "it_mw": None,
        "critical_mw": 175,
        "buildings": None,
        "high_density": None,
        "liquid_cool": None,
        "value_usd": None,
        "status": "watching",
        "owner": "CleanSpark, Inc.",
        "developer": "CleanSpark, Inc.",
        "tenant": None,
        "gc": None,
        "mep": None,
        "utility": None,
        "cxa_incumbent": None,
        "tab": None,
        "electrical_contractor": None,
        "mechanical_contractor": None,
        "oem_vendors": [],
        "bd_owner_internal": None,
        "cx_award_status": "open",
        "relationship": "unknown",
        "dates": dates(RFS="2027-11-01", L3="2027-11-01"),
        "scope_fit": dict(EMPTY_SCOPE),
        "next_action": "Map CleanSpark Cx buyer and GC on Sandersville. Do not outbound the unnamed tenant.",
        "next_action_due": "2026-09-25",
        "sources": [
            src(
                "primary",
                "CleanSpark, Inc. owner PR: 175 MW critical IT load; 20-year NNN lease to a confidential high-IG global technology company; deliveries expected to begin Q4 2027. Tenant legal name unknown. GC / CxA / L-stages unknown.",
                "2026-07-14",
                "https://www.prnewswire.com/news-releases/cleanspark-secures-twenty-year-lease-with-high-investment-grade-global-technology-company-for-data-center-in-sandersville-georgia-302824483.html",
            )
        ],
        "field_confidence": {
            "name": "confirmed",
            "city": "confirmed",
            "state": "confirmed",
            "region": "confirmed",
            "owner": "confirmed",
            "developer": "confirmed",
            "critical_mw": "inferred",
            "dates.L3": "inferred",
            "dates.RFS": "inferred",
            "cx_award_status": "inferred",
            "relationship": "unknown",
            "tenant": "unknown",
            "gc": "unknown",
            "it_mw": "unknown",
            "value_usd": "unknown",
        },
        "notes": "Ingested from DQ-HUNT-CLEANSPARK-SANDERSVILLE.md (updated 2026-09-18). Hunt Radar line: 78 develop. L3 is inferred from owner-named Q4 2027 delivery start (hunt forbids inventing a separate COD). $6.6B contracted revenue is tenant lease language — not Cx value_usd. Tenant legal name unknown.",
    }
)

projects.append(
    {
        "project_id": "dq-hunt-vantage-frontier",
        "name": "Vantage Frontier Abilene",
        "aliases": [
            "Frontier",
            "Vantage Frontier Shackelford",
            "DQ-HUNT-VANTAGE-FRONTIER",
            "TX3",
            "TX309",
        ],
        "campus": "Frontier",
        "building": "TX3",
        "city": "Abilene",
        "state": "TX",
        "country": "US",
        "region": "TX",
        "dq_number": None,
        "record_kind": "live",
        "project_type": "hyperscale",
        "it_mw": 1400,
        "critical_mw": None,
        "buildings": 10,
        "high_density": True,
        "liquid_cool": True,
        "value_usd": None,
        "status": "watching",
        "owner": "Vantage Data Centers",
        "developer": "TX309 LLC",
        "tenant": None,
        "gc": None,
        "mep": None,
        "utility": None,
        "cxa_incumbent": None,
        "tab": "TABS2026024111",
        "electrical_contractor": None,
        "mechanical_contractor": None,
        "oem_vendors": [],
        "bd_owner_internal": None,
        "cx_award_status": "unknown",
        "relationship": "unknown",
        "dates": dates(
            announcement="2025-08-19",
            sitework="2026-04-22",
            L3="2027-11-12",
        ),
        "scope_fit": dict(EMPTY_SCOPE),
        "next_action": "Ask whether Cx is campus-wide vs per-building, and who owns CxA / IST while GC is still open.",
        "next_action_due": "2026-09-25",
        "sources": [
            src(
                "primary",
                "Vantage Data Centers unveils plans for Frontier, a 1.4 GW mega-campus in Texas (Shackelford / Abilene): 10 data centers, 1,200 acres, 3.7M sq ft, liquid cooling, 250kW+ racks. Construction begun; first building delivery H2 2026.",
                "2025-08-19",
                "https://vantage-dc.com/news/vantage-data-centers-unveils-plans-for-frontier-a-25b-mega-campus-in-texas-to-meet-unprecedented-ai-demand/",
            ),
            src(
                "primary",
                "TABS TX3 / TX309: 246 PR 1604 Bldg 9; start 2026-04-22 complete 2027-11-12; design firm Kiewit; 398,117 sf; est. construction cost $1.161B (construction, not Cx).",
                "2026-06-29",
                "https://www.tdlr.texas.gov/TABS/Projects/TABS2026024111",
            ),
        ],
        "field_confidence": {
            "name": "confirmed",
            "city": "confirmed",
            "state": "confirmed",
            "region": "confirmed",
            "owner": "confirmed",
            "developer": "confirmed",
            "buildings": "confirmed",
            "liquid_cool": "confirmed",
            "high_density": "confirmed",
            "tab": "confirmed",
            "dates.L3": "confirmed",
            "dates.sitework": "confirmed",
            "it_mw": "confirmed",
            "critical_mw": "unknown",
            "cx_award_status": "unknown",
            "relationship": "unknown",
            "gc": "unknown",
            "tenant": "unknown",
            "value_usd": "unknown",
        },
        "notes": "Ingested from DQ-HUNT-VANTAGE-FRONTIER.md (updated 2026-09-18). Hunt Radar line: 78 develop. it_mw 1400 is the owner-named 1.4 GW campus scale (not a sourced hall IT MW). $1.161B TABS cost and $25B campus investment are not Cx value_usd. Kiewit is TABS design firm, not GC. Distinct from Vantage TX12 San Antonio.",
    }
)

projects.append(
    {
        "project_id": "dq-hunt-beale-marana",
        "name": "Beale Luckett Road Marana",
        "aliases": ["Beale Marana", "Luckett Road", "DQ-HUNT-BEALE-MARANA"],
        "campus": "Luckett Road",
        "building": None,
        "city": "Marana",
        "state": "AZ",
        "country": "US",
        "region": "AZ",
        "dq_number": None,
        "record_kind": "live",
        "project_type": "hyperscale",
        "it_mw": None,
        "critical_mw": 550,
        "buildings": None,
        "high_density": None,
        "liquid_cool": False,
        "value_usd": None,
        "status": "watching",
        "owner": "Beale Infrastructure",
        "developer": "Beale Infrastructure",
        "tenant": None,
        "gc": None,
        "mep": None,
        "utility": "TEP/Trico",
        "cxa_incumbent": None,
        "tab": None,
        "electrical_contractor": None,
        "mechanical_contractor": None,
        "oem_vendors": [],
        "bd_owner_internal": None,
        "cx_award_status": "open",
        "relationship": "none",
        "dates": dates(sitework="2027-04-01", L3="2027-06-01"),
        "scope_fit": dict(EMPTY_SCOPE),
        "next_action": "Who owns CxA selection on Marana — Beale, future GC, or tenant — and which parcel phases first?",
        "next_action_due": "2026-09-25",
        "sources": [
            src(
                "internal",
                "DAY3-OPEN-CARD / POST-RACE-BD-CARD: Beale Luckett Road Marana. Construction window Q1/Q2 2027. TEP/Trico. Air-cooled. GC and CxA still open. 550 MW lower bound only (do not invent tenant). Radar 78 develop.",
                "2026-09-18",
            )
        ],
        "field_confidence": {
            "name": "confirmed",
            "city": "confirmed",
            "state": "confirmed",
            "region": "confirmed",
            "owner": "confirmed",
            "developer": "confirmed",
            "utility": "confirmed",
            "liquid_cool": "confirmed",
            "critical_mw": "inferred",
            "dates.L3": "inferred",
            "dates.sitework": "inferred",
            "cx_award_status": "inferred",
            "relationship": "inferred",
            "gc": "unknown",
            "tenant": "unknown",
            "it_mw": "unknown",
            "value_usd": "unknown",
        },
        "notes": "Ingested from DAY3-OPEN-CARD.md and POST-RACE-BD-CARD.md (2026-09-18). DQ-HUNT-BEALE-MARANA.md was named on the card but not present on Drive. 550 MW is the card's lower bound (inferred). L3 inferred from Q1/Q2 2027 construction window — not a permit complete date. No tenant invented.",
    }
)

projects.append(
    {
        "project_id": "dq-hunt-stack-dfw02-lancaster",
        "name": "STACK DFW02 Lancaster",
        "aliases": ["DFW02", "DFW02A", "DQ-HUNT-STACK-DFW02-LANCASTER", "SI DFW02A"],
        "campus": "DFW02",
        "building": "DFW02A",
        "city": "Lancaster",
        "state": "TX",
        "country": "US",
        "region": "TX",
        "dq_number": None,
        "record_kind": "live",
        "project_type": "colo",
        "it_mw": None,
        "critical_mw": 220,
        "buildings": 6,
        "high_density": None,
        "liquid_cool": None,
        "value_usd": None,
        "status": "watching",
        "owner": "STACK Infrastructure",
        "developer": "SI DFW02A, LLC",
        "tenant": None,
        "gc": None,
        "mep": None,
        "utility": None,
        "cxa_incumbent": None,
        "tab": "TABS2025010772",
        "electrical_contractor": None,
        "mechanical_contractor": None,
        "oem_vendors": [],
        "bd_owner_internal": None,
        "cx_award_status": "unknown",
        "relationship": "unknown",
        "dates": dates(
            announcement="2025-01-30",
            sitework="2025-05-21",
            L3="2027-03-01",
        ),
        "scope_fit": dict(EMPTY_SCOPE),
        "next_action": "Map STACK DFW02 Cx path (campus-wide vs per-building). Prefer TDLR dates + DCD campus MW. Distinct from Stack Berry Hill.",
        "next_action_due": "2026-09-30",
        "sources": [
            src(
                "primary",
                "TDLR TABS2025010772: STACK DFW02A, 1000 E Beltline Road, Lancaster TX, Dallas County. Privately funded new construction. Start 2025-05-21 complete 2027-03-01. Registered 2025-01-30. Design Corgan. 360,028 SF. Est. construction cost ~$79.7M (not Cx fee / not IT MW). GC/Cx unknown. IT MW not on TABS.",
                "2025-01-30",
                "https://www.tdlr.texas.gov/TABS/Projects/TABS2025010772",
            ),
            src(
                "secondary",
                "DCD (Apr 30, 2024): STACK announces ~220 MW Lancaster campus (DFW2), six buildings, mid-2026 delivery framing, Oncor on-site substation language — campus MW context, not confirmed COD.",
                "2024-04-30",
            ),
        ],
        "field_confidence": {
            "name": "confirmed",
            "city": "confirmed",
            "state": "confirmed",
            "region": "confirmed",
            "owner": "confirmed",
            "developer": "confirmed",
            "tab": "confirmed",
            "dates.L3": "confirmed",
            "dates.sitework": "confirmed",
            "critical_mw": "confirmed",
            "buildings": "inferred",
            "relationship": "unknown",
            "gc": "unknown",
            "it_mw": "unknown",
            "value_usd": "unknown",
            "cx_award_status": "unknown",
        },
        "notes": "Ingested from DQ-HUNT-STACK-DFW02-LANCASTER.md (2026-09-17). Hunt score rationale: campus ~220 MW + TABS complete Mar 1 2027 + TX + owner STACK / design Corgan (GC unk) + Cx unk. Never invent hall IT MW from TABS cost. Distinct from Stack Berry Hill.",
    }
)

projects.append(
    {
        "project_id": "example-north-texas-ai",
        "name": "North Texas AI Campus",
        "aliases": ["NTX-AI EXAMPLE", "Radar enrichment template"],
        "campus": "North Texas AI Campus",
        "building": "Hall A",
        "city": "North Texas (unspecified)",
        "state": "TX",
        "country": "US",
        "region": "TX",
        "dq_number": "EXAMPLE-000",
        "record_kind": "example",
        "project_type": "AI/HPC",
        "it_mw": 120,
        "critical_mw": 132,
        "buildings": 2,
        "high_density": True,
        "liquid_cool": None,
        "value_usd": 2400000,
        "status": "active_pursuit",
        "owner": "EXAMPLE Owner LLC",
        "developer": "EXAMPLE Dev Partners",
        "tenant": "EXAMPLE hyperscale tenant (unnamed)",
        "gc": "EXAMPLE GC",
        "mep": "EXAMPLE MEP",
        "utility": None,
        "cxa_incumbent": None,
        "tab": None,
        "electrical_contractor": "EXAMPLE Electric",
        "mechanical_contractor": "EXAMPLE Mechanical",
        "oem_vendors": ["EXAMPLE Switchgear OEM", "EXAMPLE UPS OEM"],
        "bd_owner_internal": "EXAMPLE — BD desk",
        "cx_award_status": "open",
        "relationship": "prior",
        "dates": dates(
            announcement="2025-01-18",
            sitework="2026-06-18",
            shell="2026-11-18",
            permanent_power="2027-05-18",
            L0="2027-01-18",
            L1="2027-03-18",
            L2="2027-06-18",
            L3="2027-09-18",
            L4="2027-11-18",
            L5="2028-01-18",
            L6="2028-03-18",
            IST="2028-01-18",
            RFS="2028-05-18",
        ),
        "scope_fit": {
            "L0": "medium",
            "L1": "medium",
            "L2": "high",
            "L3": "high",
            "L4": "high",
            "L5": "high",
            "L6": "medium",
            "IST": "high",
            "scripts": "high",
            "FAT": "medium",
            "TAB": "unknown",
            "QAQC": "medium",
        },
        "next_action": "EXAMPLE: request Cx spec + IST matrix from GC. Confirm utility and TAB (NEED tags).",
        "next_action_due": "2026-09-25",
        "sources": [
            src(
                "example",
                "EXAMPLE SOURCE — not a real filing. Used to show how a fully enriched Radar record looks, including NEED tags for remaining holes.",
                "2026-09-17",
                "https://example.invalid/north-texas-ai-campus",
            ),
            src(
                "example",
                "EXAMPLE: value_usd $2,400,000 is a labeled demo Cx-scope figure, not a live pursuit.",
                "2026-09-17",
            ),
        ],
        "field_confidence": {
            "name": "confirmed",
            "region": "confirmed",
            "project_type": "confirmed",
            "it_mw": "confirmed",
            "critical_mw": "inferred",
            "value_usd": "confirmed",
            "owner": "confirmed",
            "gc": "confirmed",
            "dates.L3": "confirmed",
            "utility": "unknown",
            "tab": "unknown",
            "cxa_incumbent": "unknown",
            "liquid_cool": "unknown",
        },
        "notes": "EXAMPLE RECORD — not a real DataQuestCX pursuit. Shows a complete who/what/when plus NEED tags on utility, TAB, CxA incumbent, and liquid cooling. Do not mix this into live pipeline math.",
    }
)

payload = {
    "exported_at": "2026-09-18",
    "seed_version": "post-race-2026-09-18",
    "note": "Post-race Radar seed. The 104-row live projects.json from the listen workspace did not land in this GitHub checkout; this file is only records sourced from repo seed plus Drive hunt/BD cards (CleanSpark, Frontier, Beale, STACK). Scores are computed by lib/scoring.ts on ingest — not copied as magic numbers.",
    "projects": projects,
}

out = Path("/workspace/data/projects.json")
out.write_text(json.dumps(payload, indent=2) + "\n")
print(f"wrote {out} ({len(projects)} projects)")
